# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ed76d93bb29837ff681fa9c7eac1fb2bfb47efc93b696a9e608213506a28d046b8f135dd533b0a73c9bfcbd03af11b05c9a348a464c9b4751916e214dd22ff3

test:
  secret_key_base: 3d151ab3ba5d52bc7ff8dbc5d8742ad54f19600a868e5580130305e8929140a4caedbf524374e420fde81d0e58d7afeb8d6324e00b7d6d57d76ac5a3d1d86abd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
